name: bioformats2raw
channels:
  - defaults
dependencies:
  - python >=3.9
  - numpy
  - pandas
  - gradle >=7.4
  - openjdk >=8
  #- libblosc1
  #- bioformats2raw  # This should match the package name specified in the conda recipe

