package:
  name: bioformats2raw
  version: 0.6.1

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  script_env:
    - GRADLE_OPTS="-Dorg.gradle.daemon=false"

requirements:
  build:
    - python >=3.9
    - numpy
    - pandas
    - gradle =7.4.2
    - openjdk >=8

  run:
    - python >=3.9
    - numpy
    - pandas
    - openjdk >=8

test:
  commands:
    - bioformats2raw --help

about:
  home: https://github.com/jason-weirather/bioformats2raw
  license: GPL
  summary: 'A tool to convert image file formats to an intermediate Zarr structure compatible with the OME-NGFF specification'

